apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-livestream
  namespace: softnet-beta
spec:
  selector:
    matchLabels:
      app: cp-livestream
  replicas: 1
  template:
    metadata:
      labels:
        app: cp-livestream
    spec:
     containers:
     - name: cp-livestream
       image: 100.67.53.134:8082/cp-livestream:1.0
       imagePullPolicy: "Always"
       stdin: true
       tty: true
       ports:
       - containerPort: 3030
       imagePullPolicy: Always
     imagePullSecrets:
     - name: regcred
     restartPolicy: Always